const chevronright=<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth="1.5" stroke="currentColor" className="w-5 h-5 Portable:w-5 Portable:h-5">
<path strokeLinecap="round" strokeLinejoin="round" d="m8.25 4.5 7.5 7.5-7.5 7.5" />
</svg>
const cadenas='https://assets-global.website-files.com/62a8969da1ab561666c8c408/63ec5cbdb3a02f59d61cf351_material-symbols_lock.svg'


const play=<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth="1.5" stroke="currentColor" className="w-6 h-6">
<path strokeLinecap="round" strokeLinejoin="round" d="M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z" />
<path strokeLinecap="round" strokeLinejoin="round" d="M15.91 11.672a.375.375 0 0 1 0 .656l-5.603 3.113a.375.375 0 0 1-.557-.328V8.887c0-.286.307-.466.557-.327l5.603 3.112Z" />
</svg>

const fiche=<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth="1.5" stroke="currentColor" className="w-6 h-6">
<path strokeLinecap="round" strokeLinejoin="round" d="m16.862 4.487 1.687-1.688a1.875 1.875 0 1 1 2.652 2.652L10.582 16.07a4.5 4.5 0 0 1-1.897 1.13L6 18l.8-2.685a4.5 4.5 0 0 1 1.13-1.897l8.932-8.931Zm0 0L19.5 7.125M18 14v4.75A2.25 2.25 0 0 1 15.75 21H5.25A2.25 2.25 0 0 1 3 18.75V8.25A2.25 2.25 0 0 1 5.25 6H10" />
</svg>





export const NavigatCours=[

    {
        id:1,
        chevronR:{chevronright},
        titleelement:'introduction',
        CadenasClose:`${cadenas}`,
        Nombrecours:'6 Topics',
        sousMenu:{
            titreLesson:'Lesson content',
            playObject:{play},
            cours1:"course introduction (03:11)",
            cours2:'Problem Statement (Meeting with Dasher Team) (06:29)',
            cours3:'Introducing Github Actions (09:42)',
            cours4:'Basics of CI CD (08:48)',
            cours5:'create & Explore GitHub Account (05:01)',
            Fiche:{fiche},
            cours6:'Join Our Community',
            cours7:'',
            cours8:'',
            cours9:'',
            cours10:'',
            cours11:'',
            cours12:'',
            cours13:'',
            cours14:'',
            cours15:'',
            cours16:'',
            cours17:'',
            cours18:'',
            cours19:'',
            cours20:'',
            cours21:'',
            cours22:'',
            cours23:'',
            cours24:'',
            cours25:'',
            cours26:'',
            cours27:'',
            cours28:'',
            
        }

    },
    {
        id:2,
        chevronR:{chevronright},
        titleelement:'GitHub Actions - Core Concepts',
        CadenasClose:`${cadenas}`,
        Nombrecours:'24 Topics',
        sousMenu:{
            titreLesson:'lesson content',
            playObject:{play},
            cours1:"course introduction (03:11)",
            cours2:'Problem Statement (Meeting with Dasher Team) (06:29)',
            cours3:'Introducing Github Actions (09:42)',
            cours4:'Basics of CI CD (08:48)',
            cours5:'create & Explore GitHub Account (05:01)',
            Fiche:{fiche},
            cours6:'Join Our Community',
            cours7:'',
            cours8:'',
            cours9:'',
            cours10:'',
            cours11:'',
            cours12:'',
            cours13:'',
            cours14:'',
            cours15:'',
            cours16:'',
            cours17:'',
            cours18:'',
            cours19:'',
            cours20:'',
            cours21:'',
            cours22:'',
            cours23:'',
            cours24:'',
            cours25:'',
            cours26:'',
            cours27:'',
            cours28:'',
        }   
        
    },
    {
        id:3,
        chevronR:{chevronright},
        titleelement:'Continuous Integration with GitHub Actions',
        CadenasClose:`${cadenas}`,
        Nombrecours:'27 Topics',
        sousMenu:{
            titreLesson:'Lesson content',
            playObject:{play},
            cours1:"course introduction (03:11)",
            cours2:'Problem Statement (Meeting with Dasher Team) (06:29)',
            cours3:'Introducing Github Actions (09:42)',
            cours4:'Basics of CI CD (08:48)',
            cours5:'create & Explore GitHub Account (05:01)',
            Fiche:{fiche},
            cours6:'Join Our Community',
            cours7:'',
            cours8:'',
            cours9:'',
            cours10:'',
            cours11:'',
            cours12:'',
            cours13:'',
            cours14:'',
            cours15:'',
            cours16:'',
            cours17:'',
            cours18:'',
            cours19:'',
            cours20:'',
            cours21:'',
            cours22:'',
            cours23:'',
            cours24:'',
            cours25:'',
            cours26:'',
            cours27:'',
            cours28:'',
        }   
        
    },
    {
        id:4,
        chevronR:{chevronright},
        titleelement:'Continuous Deployment with GitHub Actions',
        CadenasClose:`${cadenas}`,
        Nombrecours:'15 Topics',
        sousMenu:{
            titreLesson:'Lesson content',
            playObject:{play},
            cours1:"course introduction (03:11)",
            cours2:'Problem Statement (Meeting with Dasher Team) (06:29)',
            cours3:'Introducing Github Actions (09:42)',
            cours4:'Basics of CI CD (08:48)',
            cours5:'create & Explore GitHub Account (05:01)',
            Fiche:{fiche},
            cours6:'Join Our Community',
            cours7:'',
            cours8:'',
            cours9:'',
            cours10:'',
            cours11:'',
            cours12:'',
            cours13:'',
            cours14:'',
            cours15:'',
            cours16:'',
            cours17:'',
            cours18:'',
            cours19:'',
            cours20:'',
            cours21:'',
            cours22:'',
            cours23:'',
            cours24:'',
            cours25:'',
            cours26:'',
            cours27:'',
            cours28:'',
        }   
        
    },
    {
        id:5,
        chevronR:{chevronright},
        titleelement:'Reusable Workflows and Reporting',
        CadenasClose:`${cadenas}`,
        Nombrecours:'12 Topics',
        sousMenu:{
            titreLesson:'Lesson content',
            playObject:{play},
            cours1:"course introduction (03:11)",
            cours2:'Problem Statement (Meeting with Dasher Team) (06:29)',
            cours3:'Introducing Github Actions (09:42)',
            cours4:'Basics of CI CD (08:48)',
            cours5:'create & Explore GitHub Account (05:01)',
            Fiche:{fiche},
            cours6:'Join Our Community',
            cours7:'',
            cours8:'',
            cours9:'',
            cours10:'',
            cours11:'',
            cours12:'',
            cours13:'',
            cours14:'',
            cours15:'',
            cours16:'',
            cours17:'',
            cours18:'',
            cours19:'',
            cours20:'',
            cours21:'',
            cours22:'',
            cours23:'',
            cours24:'',
            cours25:'',
            cours26:'',
            cours27:'',
            cours28:'',
        }   
        
    },
    {
        id:6,
        chevronR:{chevronright},
        titleelement:'Self Hosted Runner',
        CadenasClose:`${cadenas}`,
        Nombrecours:'7 Topics',
        sousMenu:{
            titreLesson:'Lesson content',
            playObject:{play},
            cours1:"course introduction (03:11)",
            cours2:'Problem Statement (Meeting with Dasher Team) (06:29)',
            cours3:'Introducing Github Actions (09:42)',
            cours4:'Basics of CI CD (08:48)',
            cours5:'create & Explore GitHub Account (05:01)',
            Fiche:{fiche},
            cours6:'Join Our Community',
            cours7:'',
            cours8:'',
            cours9:'',
            cours10:'',
            cours11:'',
            cours12:'',
            cours13:'',
            cours14:'',
            cours15:'',
            cours16:'',
            cours17:'',
            cours18:'',
            cours19:'',
            cours20:'',
            cours21:'',
            cours22:'',
            cours23:'',
            cours24:'',
            cours25:'',
            cours26:'',
            cours27:'',
            cours28:'',
        }   
        
    },
    {
        id:7,
        chevronR:{chevronright},
        titleelement:'Security Guide',
        CadenasClose:`${cadenas}`,
        Nombrecours:'7 Topics',
        sousMenu:{
            titreLesson:'Lesson content',
            playObject:{play},
            cours1:"course introduction (03:11)",
            cours2:'Problem Statement (Meeting with Dasher Team) (06:29)',
            cours3:'Introducing Github Actions (09:42)',
            cours4:'Basics of CI CD (08:48)',
            cours5:'create & Explore GitHub Account (05:01)',
            Fiche:{fiche},
            cours6:'Join Our Community',
            cours7:'',
            cours8:'',
            cours9:'',
            cours10:'',
            cours11:'',
            cours12:'',
            cours13:'',
            cours14:'',
            cours15:'',
            cours16:'',
            cours17:'',
            cours18:'',
            cours19:'',
            cours20:'',
            cours21:'',
            cours22:'',
            cours23:'',
            cours24:'',
            cours25:'',
            cours26:'',
            cours27:'',
            cours28:'',
        }   
        
    },

    {
        id:8,
        chevronR:{chevronright},
        titleelement:'Custom Actions',
        CadenasClose:`${cadenas}`,
        Nombrecours:'9 Topics',
        sousMenu:{
            titreLesson:'Lesson content',
            playObject:{play},
            cours1:"course introduction (03:11)",
            cours2:'Problem Statement (Meeting with Dasher Team) (06:29)',
            cours3:'Introducing Github Actions (09:42)',
            cours4:'Basics of CI CD (08:48)',
            cours5:'create & Explore GitHub Account (05:01)',
            Fiche:{fiche},
            cours6:'Join Our Community',
            cours7:'',
            cours8:'',
            cours9:'',
            cours10:'',
            cours11:'',
            cours12:'',
            cours13:'',
            cours14:'',
            cours15:'',
            cours16:'',
            cours17:'',
            cours18:'',
            cours19:'',
            cours20:'',
            cours21:'',
            cours22:'',
            cours23:'',
            cours24:'',
            cours25:'',
            cours26:'',
            cours27:'',
            cours28:'',
        }   
        
    },
]